platform :ios, '7.0'

pod 'RNTimer', '~> 0.0.1'
pod 'NSString-UrlEncode', '~> 1.1.0'
pod 'GDChannel', '~> 0.5'
pod 'MBProgressHUD', '~> 0.9.1'
pod 'Mantle', '~> 2.0.2'
pod 'ReactiveCocoa', '~> 2.5'
pod 'ReactiveViewModel', '~> 0.3'
pod 'AFNetworking', '~>2.5.4'
pod 'AFNetworking-RACExtensions', '~> 0.1.8'
pod 'SSKeychain'